import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {MindARThree} from 'mindar-image-three';
import {Compiler} from 'mindar-image';
const qs=new URLSearchParams(location.search);let exp;try{exp=JSON.parse(decodeURIComponent(qs.get('experience')||''))}catch{}
let soundEnabled=true,audioCtx=null;function audio(){if(!soundEnabled)return null;audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}function tone(freq,d=.1,type='sine',gain=.03,delay=0){const c=audio();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime+delay);g.gain.setValueAtTime(.0001,c.currentTime+delay);g.gain.exponentialRampToValueAtTime(gain,c.currentTime+delay+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+delay+d);o.connect(g).connect(c.destination);o.start(c.currentTime+delay);o.stop(c.currentTime+delay+d+.03)}const sfx={tap(){tone(520,.055,'sine',.02)},ready(){tone(300,.08,'triangle',.018);tone(600,.1,'sine',.018,.07)},found(){tone(392,.16,'sine',.025);tone(659,.2,'sine',.025,.08);tone(988,.26,'sine',.018,.16)},lost(){tone(290,.08,'triangle',.015);tone(210,.12,'sine',.012,.07)}};
const fatal=message=>{document.getElementById('fatalMessage').textContent=message;document.getElementById('fatal').hidden=false};if(!exp)fatal('No AR experience was selected. Return to the gallery and choose an artwork.');
document.getElementById('arTitle').textContent=exp?.title?.toUpperCase()||'AR SCAN';document.getElementById('targetImage').src=exp?.demoTargetImage||exp?.artwork||'';
document.getElementById('exitBtn').addEventListener('click',()=>{sfx.tap();setTimeout(()=>location.href='index.html',80)});document.getElementById('helpBtn').addEventListener('click',()=>{sfx.tap();document.getElementById('targetModal').hidden=false});document.getElementById('targetClose').addEventListener('click',()=>{sfx.tap();document.getElementById('targetModal').hidden=true});document.getElementById('soundBtn').addEventListener('click',e=>{soundEnabled=!soundEnabled;e.currentTarget.textContent=soundEnabled?'♪':'×';if(soundEnabled)sfx.ready()});
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error(`Could not load target image: ${src}`));img.src=src})}
async function compileTargetFromImage(src,onProgress){if(typeof Compiler!=='function')throw new Error('The image-tracking compiler could not initialize. Reload the page in Chrome or Safari and try again.');const img=await loadImage(src),compiler=new Compiler();await compiler.compileImageTargets([img],p=>onProgress?.(p));const exportedBuffer=await compiler.exportData(),blob=new Blob([exportedBuffer],{type:'application/octet-stream'});return URL.createObjectURL(blob)}
async function resolveTargetSource(statusLabel,statusTitle,statusHelp){if(exp.targetMode!=='runtime')return exp.target;const wrap=document.getElementById('compileProgress'),bar=document.getElementById('compileProgressBar');wrap.hidden=false;statusLabel.textContent='PREPARING TARGET';statusTitle.textContent='Learning this artwork';statusHelp.textContent='The first scan may take a moment while the image target is prepared in your browser.';const url=await compileTargetFromImage(exp.targetSourceImage||exp.artwork,p=>{const pct=Math.max(0,Math.min(100,Number(p)||0));bar.style.width=`${pct}%`;statusLabel.textContent=`PREPARING TARGET · ${pct.toFixed(0)}%`});bar.style.width='100%';setTimeout(()=>wrap.hidden=true,350);return url}
function makeEffects(group){const ringGeo=new THREE.RingGeometry(.42,.46,64),ringMat=new THREE.MeshBasicMaterial({color:0xb9ff4f,transparent:true,opacity:.0,side:THREE.DoubleSide,depthWrite:false}),ring=new THREE.Mesh(ringGeo,ringMat);ring.rotation.x=-Math.PI/2;ring.position.z=.02;group.add(ring);const count=70,pos=new Float32Array(count*3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=.18+Math.random()*.55;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=(Math.random()-.5)*.55;pos[i*3+2]=Math.sin(a)*r}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const mat=new THREE.PointsMaterial({color:0xb9ff4f,size:.012,transparent:true,opacity:0,depthWrite:false});const points=new THREE.Points(geo,mat);group.add(points);return{ring,points,ringMat,pointsMat:mat,time:0,active:false}}
async function start(){if(!exp)return;if(!window.isSecureContext&&location.hostname!=='localhost'){fatal('Camera access requires HTTPS (or localhost). Host this project on an HTTPS-enabled service before testing on a phone.');return}const label=document.getElementById('statusLabel'),title=document.getElementById('statusTitle'),help=document.getElementById('statusHelp'),panel=document.getElementById('statusPanel'),frame=document.querySelector('.scan-frame'),flash=document.getElementById('foundFlash');let compiledTargetUrl=null;try{label.textContent='CAMERA PERMISSION';title.textContent='Allow camera access';help.textContent='Your camera feed stays in the browser and is used to recognize the selected artwork.';const preflight=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});preflight.getTracks().forEach(t=>t.stop());sfx.ready();compiledTargetUrl=await resolveTargetSource(label,title,help);const root=document.getElementById('arRoot'),mindarThree=new MindARThree({container:root,imageTargetSrc:compiledTargetUrl,maxTrack:1,filterMinCF:.0001,filterBeta:.001}),{renderer,scene,camera}=mindarThree;renderer.outputColorSpace=THREE.SRGBColorSpace;scene.add(new THREE.HemisphereLight(0xffffff,0x444444,2.3));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(1,2,2);scene.add(key);const anchor=mindarThree.addAnchor(0);
const dracoLoader=new DRACOLoader();
dracoLoader.setDecoderPath('https://unpkg.com/three@0.160.0/examples/jsm/libs/draco/gltf/');
dracoLoader.setDecoderConfig({type:'wasm'});
dracoLoader.preload();
const loader=new GLTFLoader();
loader.setDRACOLoader(dracoLoader);
const gltf=await loader.loadAsync(exp.model);
dracoLoader.dispose();
const model=gltf.scene,s=Number(exp.modelScale||.5);const baseX=Number(exp.modelX||0),baseY=Number(exp.modelY||0),baseZ=Number(exp.modelZ||.05);model.scale.setScalar(s);model.position.set(baseX,baseY,baseZ);model.rotation.set(Number(exp.modelRotX||0),Number(exp.modelRotY||0),Number(exp.modelRotZ||0));anchor.group.add(model);const effects=makeEffects(anchor.group);let mixer=null;if(gltf.animations?.length){mixer=new THREE.AnimationMixer(model);gltf.animations.forEach(clip=>mixer.clipAction(clip).play())}let popActive=false,popProgress=0;if(exp.popOut){model.scale.setScalar(s*.84);model.position.set(baseX,baseY,baseZ-.06);}
anchor.onTargetFound=()=>{label.textContent='SIGNAL FOUND';title.textContent='Experience unlocked';help.textContent='Keep the artwork in view. Move your phone slightly to explore the object.';frame.style.opacity='.18';frame.style.transform='translate(-50%,-50%) scale(1.04)';panel.classList.add('found');flash.classList.remove('active');void flash.offsetWidth;flash.classList.add('active');effects.active=true;effects.time=0;if(exp.popOut){popActive=true;popProgress=0;model.scale.setScalar(s*.84);model.position.set(baseX,baseY,baseZ-.06);}sfx.found()};anchor.onTargetLost=()=>{label.textContent='SEARCHING';title.textContent='Find the artwork again';help.textContent='Center the complete design inside the frame with good lighting.';frame.style.opacity='1';frame.style.transform='translate(-50%,-50%) scale(1)';panel.classList.remove('found');effects.active=false;popActive=false;sfx.lost()};label.textContent='SEARCHING';title.textContent='Point at the selected artwork';help.textContent='Keep the full design visible, flat, and well lit.';await mindarThree.start();const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const delta=clock.getDelta();if(mixer)mixer.update(delta);if(exp.popOut&&popActive&&popProgress<1){popProgress=Math.min(1,popProgress+delta*2.4);const eased=1-Math.pow(1-popProgress,3);model.scale.setScalar(THREE.MathUtils.lerp(s*.84,s,eased));model.position.set(baseX,baseY,THREE.MathUtils.lerp(baseZ-.06,baseZ,eased));}if(!gltf.animations?.length&&exp.idleSpin!==false)model.rotation.y+=delta*.42;if(effects.active){effects.time+=delta;effects.ringMat.opacity=Math.max(0,.7-effects.time*.22);effects.pointsMat.opacity=.65;effects.ring.scale.setScalar(1+(effects.time%1.4)*.35);effects.ring.rotation.z+=delta*.55;effects.points.rotation.y+=delta*.35;effects.points.rotation.x+=delta*.08}else{effects.ringMat.opacity*=.9;effects.pointsMat.opacity*=.9}renderer.render(scene,camera)});document.getElementById('exitBtn').addEventListener('click',async()=>{renderer.setAnimationLoop(null);try{mindarThree.stop()}catch{}if(compiledTargetUrl?.startsWith('blob:'))URL.revokeObjectURL(compiledTargetUrl)},{once:true})}catch(err){console.error(err);if(compiledTargetUrl?.startsWith('blob:'))URL.revokeObjectURL(compiledTargetUrl);let reason;if(err?.name==='NotAllowedError'){reason='Camera permission was denied. Enable camera access for this site and try again.';}else if(String(err?.message||err).toLowerCase().includes('draco')){reason='The 3D model uses Draco compression, but its decoder could not load. Check that this page can access the Three.js decoder CDN, then reload.';}else{reason=`Could not start the AR scanner: ${err?.message||'Unknown error'}`;}fatal(reason)}}start();
